---
- name: Reset vCenter Appliance Password
  hosts: all
  tasks:
    - name: Change vCenter root password
      shell:  ls -l
      #command: "echo {{ new_password }} | passwd --stdin root"
      register: output
      #validate_certs: false
      #delgate_to: 10.115.49.203
      
