---
- name: Reset vCenter Appliance Password
  hosts: all
  tasks:
    - name: Change vCenter root password
      command: "echo {{ new_password }} | passwd --stdin root"
      become: yes
      register: output
      delgate_to: localhost
      
