---
- name: Reset vCenter Appliance Password
  hosts: all
  #connection: local
  tasks:
    - name: Change vCenter root password
      #shell:  echo {{ new_password }} | passwd --stdin root
      command: '{ echo "{{ new_password }}";echo "{{ new_password }}"; } | passwd'
      register: output

      
