---
- hosts: all
  tasks:
   - name: delete log files
     file:
       path: "{{ item }}"
       state: absent
     register: output
     with_items: {{ command_list }}
   - name: Change vCenter root password
     command: "service-control --start --all"
     become: yes
     register: output
   - debug:
       var: output
