- hosts: all
  collections:
   - community.vmware
   
  tasks:
   - name: Remove a snapshot
     community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/vm/"
        name: "{{ guest_name }}"
        state: absent
        snapshot_name: "{{ snapshot_name }}"
        validate_certs: False
     delegate_to: localhost
