---
- hosts: all
  tasks:
   - name: delete log files
     shell: "{{ item }}"
     register: output
     with_items: "{{ command_list }}"
   - name: Restart Service
     command: "service-control --start --all"
     become: yes
     register: output
   - debug:
       var: output
