---
- hosts: all
  tasks:
   - name: delete log files
     file:
       path: "{{ item }}"
       state: absent
     register: output
     with_items: {{ command_list }}

   - debug:
       var: output
